apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gabrieljuliao-notes-app.fullname" . }}-env
  labels:
    {{- include "gabrieljuliao-notes-app.labels" . | nindent 4 }}
data:
  IS_TLS_ENABLED: {{ .Values.certMgmt.tlsEnabled | quote }}
  CONTEXT_PATH: {{ .Values.app.contextPath | quote }}
